In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)


In [3]:
# === 1. One-dimensional array: first 10 natural numbers ===
vec10 = np.arange(1, 11)
print(vec10)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# === 2. Two-dimensional 3x3 array of zeros ===
mat_zeros_3x3 = np.zeros((3, 3), dtype=int)
print(mat_zeros_3x3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
# ===3. 5x5 array of random integers [1, 10] [1, 10] ===
np.random.seed(42)
mat_rand_int_5x5 = np.random.randint(1, 11, size=(5, 5))
print(mat_rand_int_5x5)

[[ 7  4  8  5  7]
 [10  3  7  8  5]
 [ 4  8  8  3  6]
 [ 5  2  8  6  2]
 [ 5  1 10  6  9]]


In [6]:
# === 4. 4x4 array of random real numbers [0, 1) ===
mat_rand_float_4x4 = np.random.rand(4, 4)
print(mat_rand_float_4x4)

[[0.2912 0.6119 0.1395 0.2921]
 [0.3664 0.4561 0.7852 0.1997]
 [0.5142 0.5924 0.0465 0.6075]
 [0.1705 0.0651 0.9489 0.9656]]


In [7]:
# === 5. Two vectors of length 5 (random integers [1,10]) and element-wise +, -, * ===
a5 = np.random.randint(1, 11, size=5)
b5 = np.random.randint(1, 11, size=5)
print("a5:", a5)
print("b5:", b5)
print("a5 + b5 =", a5 + b5)
print("a5 - b5 =", a5 - b5)
print("a5 * b5 =", a5 * b5)

a5: [ 2 10  9 10  5]
b5: [2 4 7 8 3]
a5 + b5 = [ 4 14 16 18  8]
a5 - b5 = [0 6 2 2 2]
a5 * b5 = [ 4 40 63 80 15]


In [9]:
# === 6. The dot product of two vectors of length 7 ===
v1 = np.random.rand(7)
v2 = np.random.rand(7)
dot_v = np.dot(v1, v2)
print("v1:", v1)
print("v2:", v2)
print("Scalar product =", dot_v)

v1: [0.196  0.0452 0.3253 0.3887 0.2713 0.8287 0.3568]
v2: [0.2809 0.5427 0.1409 0.8022 0.0746 0.9869 0.7722]
Scalar product = 1.5508460520064524


In [10]:
# === 7. Product of 2x2 and 2x3 matrices (random integers [1,10]) ===
A_2x2 = np.random.randint(1, 11, size=(2, 2))
B_2x3 = np.random.randint(1, 11, size=(2, 3))
C_2x3 = A_2x2 @ B_2x3
print("A_2x2 =\n", A_2x2)
print("B_2x3 =\n", B_2x3)
print("A @ B =\n", C_2x3)

A_2x2 =
 [[8 8]
 [3 1]]
B_2x3 =
 [[ 8  3  3]
 [ 1  5 10]]
A @ B =
 [[ 72  64 104]
 [ 25  14  19]]


In [11]:
# === 8. Inverse matrix for 3x3 (random integers [1,10]) ===
while True:
    M = np.random.randint(1, 11, size=(3, 3))
    if not np.isclose(np.linalg.det(M), 0.0):
        break
M_inv = np.linalg.inv(M)
print("M =\n", M)
print("det(M) =", np.linalg.det(M))
print("M^{-1} =\n", M_inv)

M =
 [[ 7 10  9]
 [ 7  9  8]
 [ 2  1  7]]
det(M) = -43.99999999999997
M^{-1} =
 [[-1.25    1.3864  0.0227]
 [ 0.75   -0.7045 -0.1591]
 [ 0.25   -0.2955  0.1591]]


In [12]:
# === 9. 4x4 transpose (random real numbers) [0,1)) ===
T = np.random.rand(4, 4)
print("T =\n", T)
print("T.T =\n", T.T)

T =
 [[0.311  0.3252 0.7296 0.6376]
 [0.8872 0.4722 0.1196 0.7132]
 [0.7608 0.5613 0.771  0.4938]
 [0.5227 0.4275 0.0254 0.1079]]
T.T =
 [[0.311  0.8872 0.7608 0.5227]
 [0.3252 0.4722 0.5613 0.4275]
 [0.7296 0.1196 0.771  0.0254]
 [0.6376 0.7132 0.4938 0.1079]]


In [13]:
# === 10. The product of a 3x4 matrix and a vector of length 4 (integers) [1,10]) ===
M_3x4 = np.random.randint(1, 11, size=(3, 4))
v4 = np.random.randint(1, 11, size=4)
mv = M_3x4 @ v4
print("M_3x4 =\n", M_3x4)
print("v4 =", v4)
print("M_3x4 @ v4 =", mv)

M_3x4 =
 [[7 1 4 4]
 [5 7 7 4]
 [7 3 6 2]]
v4 = [10  9  5  6]
M_3x4 @ v4 = [123 172 139]


In [14]:
# === 11. Product of a 2x3 matrix by a vector of length 3 (real [0,1)) ===
M_2x3 = np.random.rand(2, 3)
u3 = np.random.rand(3)
res = M_2x3 @ u3
print("M_2x3 =\n", M_2x3)
print("u3 =", u3)
print("M_2x3 @ u3 =", res)

M_2x3 =
 [[0.4565 0.2184 0.4165]
 [0.8833 0.3243 0.1221]]
u3 = [0.3563 0.9068 0.2721]
M_2x3 @ u3 = [0.4741 0.6421]


In [15]:
# === 12. Element-wise multiplication of two 2x2 matrices (integers) [1,10]) ===
E1 = np.random.randint(1, 11, size=(2, 2))
E2 = np.random.randint(1, 11, size=(2, 2))
elem_mul = E1 * E2
print("E1 =\n", E1)
print("E2 =\n", E2)
print("E1 * E2 =\n", elem_mul)

E1 =
 [[9 4]
 [9 3]]
E2 =
 [[7 6]
 [8 9]]
E1 * E2 =
 [[63 24]
 [72 27]]


In [16]:
# === 13. Product of two 2x2 matrices (integers) [1,10]) ===
F1 = np.random.randint(1, 11, size=(2, 2))
F2 = np.random.randint(1, 11, size=(2, 2))
prod = F1 @ F2
print("F1 =\n", F1)
print("F2 =\n", F2)
print("F1 @ F2 =\n", prod)

F1 =
 [[ 5  1]
 [ 3 10]]
F2 =
 [[8 6]
 [8 9]]
F1 @ F2 =
 [[ 48  39]
 [104 108]]


In [18]:
# === 14. Sum of 5x5 elements (objectives [1,100]) ===
G = np.random.randint(1, 101, size=(5, 5))
print("G =\n", G)
print("Sum of elements =", G.sum())

G =
 [[70 32 68 55 75]
 [56 17 38 24 69]
 [98 70 86 11 16]
 [97 73 59 70 80]
 [93  3 20 59 36]]
Sum of elements = 1375


In [19]:
# === 15. The difference of two 4x4 matrices (integers [1,10]) ===
H1 = np.random.randint(1, 11, size=(4, 4))
H2 = np.random.randint(1, 11, size=(4, 4))
diff = H1 - H2
print("H1 =\n", H1)
print("H2 =\n", H2)
print("H1 - H2 =\n", diff)

H1 =
 [[ 3 10  3  3]
 [ 4  7  4  9]
 [ 1  8  7  2]
 [ 8  1  9  9]]
H2 =
 [[ 2  7 10  3]
 [ 7 10  9  4]
 [ 1  2  1  5]
 [ 5  7  9  9]]
H1 - H2 =
 [[ 1  3 -7  0]
 [-3 -3 -5  5]
 [ 0  6  6 -3]
 [ 3 -6  0  0]]


In [21]:
# === 16. Column vector of row sums for 3x3 (real [0,1)) ===
R = np.random.rand(3, 3)
row_sums_col = R.sum(axis=1, keepdims=True)
print("R =\n", R)
print("Row sums (column vector) =\n", row_sums_col)

R =
 [[0.6064 0.0092 0.1015]
 [0.6635 0.0051 0.1608]
 [0.5487 0.6919 0.652 ]]
Row sums (column vector) =
 [[0.7171]
 [0.8294]
 [1.8926]]


In [22]:
# === 17. A 3x4 matrix of arbitrary integers and a matrix with their squares ===
Q = np.random.randint(-5, 6, size=(3, 4))
Q_sq = np.square(Q)
print("Q =\n", Q)
print("Q^2 =\n", Q_sq)

Q =
 [[ 3 -2 -5 -2]
 [-5 -1 -2  2]
 [ 2  1 -3 -5]]
Q^2 =
 [[ 9  4 25  4]
 [25  1  4  4]
 [ 4  1  9 25]]


In [23]:
# === 18. Vector of length 4 (integers [1,50]) and vector of square roots ===
w = np.random.randint(1, 51, size=4)
sqrt_w = np.sqrt(w.astype(float))
print("w =", w)
print("sqrt(w) =", sqrt_w)


w = [33 48 12 22]
sqrt(w) = [5.7446 6.9282 3.4641 4.6904]


In [24]:
# === Replace all odd numbers with -1 ===
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_odd_to_minus1 = arr.copy()
arr_odd_to_minus1[arr_odd_to_minus1 % 2 == 1] = -1
print(arr_odd_to_minus1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [25]:
# === Convert a 1D array to a 2D array with 2 rows ===
arr1d = np.arange(1, 11)
arr2d_2rows = arr1d.reshape(2, -1)
print(arr2d_2rows)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
# === Vertically stack two 2D arrays ===
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
vstacked = np.vstack((a, b))
print("a =\n", a)
print("b =\n", b)
print("vstack(a, b) =\n", vstacked)

a =
 [[1 2 3]
 [4 5 6]]
b =
 [[ 7  8  9]
 [10 11 12]]
vstack(a, b) =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
# === Template without hard-coding: repeat + tile (NumPy only) ===
a = np.array([1, 2, 3])
out = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(out)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [29]:
# ===Common elements between a and b ===
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a, b)
print(common)

[2 4]


In [30]:
# === Positions of the first 5 maximum values ===
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
top5_idx = np.argsort(a)[-5:][::-1]
print("a =", a)
print("top5 indices =", top5_idx)

a = [27.6268 14.6401 21.8014 42.394   1.2312  6.9569 33.8667 41.4668  7.6986
 29.1796 44.6748 11.2509 10.0811  6.3105 11.7652 48.9526 40.7725  9.4251
 40.995  14.4296]
top5 indices = [15 10  3  7 18]


In [31]:
# === Removing NaN from a 1D array ===
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
clean = a[~np.isnan(a)]
print(clean)

[1. 2. 3. 5. 6. 7.]


In [32]:
# === Euclidean distance between two arrays ===
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a - b)
print("distance =", dist)

distance = 6.708203932499369


In [33]:
# === Index of the 5th repetition of the number 1 ===
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
idx_ones = np.flatnonzero(x == 1)
if idx_ones.size >= 5:
    print("index of 5th '1' =", idx_ones[4])
else:
    print("Less than 5 occurrences 1")

index of 5th '1' = 8


In [34]:
# ===Mark repeats (2nd occurrence and beyond) as True ===
np.random.seed(100)
a = np.random.randint(0, 5, 10)
u, inv = np.unique(a, return_inverse=True)
mask = np.zeros(a.shape, dtype=bool)
for g in range(len(u)):
    idx = np.flatnonzero(inv == g)
    mask[idx[1:]] = True
print("a =", a)
print("mask =", mask)

a = [0 0 3 0 2 4 2 2 2 2]
mask = [False  True False  True False False  True  True  True  True]
